spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=model_db
    password: '1998'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /3Dmodel
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
  port: 8189
scan:
  adressSer: G:\testJava
  adress1: F:\[3D PRINT]\Модели\[Patreon]\[Figure]
  adress2: F:\[3D PRINT]\Модели\[Patreon]\[Pack]
  adress3: F:\[3D PRINT]\Модели\[Patreon]\[Other]
webApp:
  urlPostWeb: http://localhost:8999/3Dmodel/sync/addModel
  urlGetWeb: http://localhost:8999/3Dmodel/sync/getModels