
CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE print_model
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_category  VARCHAR(255),
    model_directory VARCHAR(255),
    model_name      VARCHAR(255),
    my_rate         INTEGER,
    nsfw            BOOLEAN,
    CONSTRAINT print_model_pkey PRIMARY KEY (id)
);

CREATE TABLE print_model_web
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_category   VARCHAR(255),
    model_name       VARCHAR(255),
    model_path       VARCHAR(255),
    model_size       FLOAT8,
    my_rate          INTEGER,
    views            BIGINT,
    preview_model_id BIGINT,
    CONSTRAINT print_model_web_pkey PRIMARY KEY (id)
);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

CREATE INDEX print_model_model_name ON print_model (model_name);

CREATE INDEX print_model_web_model_name ON print_model_web (model_name);

CREATE TABLE model_other_files
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_class                  VARCHAR(255),
    model_name                  VARCHAR(255),
    name_model_oth              VARCHAR(255),
    oth_address                 VARCHAR(255),
    oth_format                  VARCHAR(255),
    oth_size                    FLOAT8,
    print_model_oth_data_set_id BIGINT,
    CONSTRAINT model_other_files_pkey PRIMARY KEY (id)
);

CREATE TABLE print_model_oth_web
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    oth_format        VARCHAR(255),
    oth_name          VARCHAR(255),
    oth_size          FLOAT8,
    oth_preview       TEXT,
    model_oth_list_id BIGINT,
    CONSTRAINT print_model_oth_web_pkey PRIMARY KEY (id)
);

CREATE TABLE print_model_tag_web
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_name     VARCHAR(255),
    count_models INTEGER,
    name_tag     VARCHAR(255),
    CONSTRAINT print_model_tag_web_pkey PRIMARY KEY (id)
);

CREATE TABLE print_model_zip_data
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    archive_ratio               INTEGER,
    file_class                  VARCHAR(255),
    model_name                  VARCHAR(255),
    name_model_oth              VARCHAR(255),
    zip_adress                  VARCHAR(255),
    zip_format                  VARCHAR(255),
    zip_size                    FLOAT8,
    print_model_zip_data_set_id BIGINT,
    CONSTRAINT print_model_zip_data_pkey PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE tags_and_models
(
    model_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL
);

CREATE TABLE tags_and_models_web
(
    model_id BIGINT NOT NULL,
    tag_id   BIGINT NOT NULL
);

CREATE TABLE watcher
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT watcher_pkey PRIMARY KEY (id)
);

CREATE TABLE watcher_roles
(
    watcher_id BIGINT NOT NULL,
    roles_id   BIGINT NOT NULL
);

ALTER TABLE watcher_roles
    ADD CONSTRAINT fk17i2f3xol5oi7slt1wriailjf FOREIGN KEY (roles_id) REFERENCES role (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags_and_models
    ADD CONSTRAINT fk2e8g558y5753ea6r6dhpm23je FOREIGN KEY (tag_id) REFERENCES print_model_tag_web (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE model_other_files
    ADD CONSTRAINT fk6borl7q70n41qbj3mucipvdve FOREIGN KEY (print_model_oth_data_set_id) REFERENCES print_model (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags_and_models_web
    ADD CONSTRAINT fkac7bwx6x0h6lic3eofn0s9ngy FOREIGN KEY (model_id) REFERENCES print_model_web (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE print_model_web
    ADD CONSTRAINT fkdwo3l83td3jt3n8v2m128y81q FOREIGN KEY (preview_model_id) REFERENCES print_model_oth_web (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags_and_models_web
    ADD CONSTRAINT fkenn2de3x1mvv1yvx376hhe9qt FOREIGN KEY (tag_id) REFERENCES print_model_tag_web (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags_and_models
    ADD CONSTRAINT fkhstdic08qirtvhxqybkhvebp5 FOREIGN KEY (model_id) REFERENCES print_model (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE print_model_zip_data
    ADD CONSTRAINT fkkx3kxggncvkvosgjjaarqndlc FOREIGN KEY (print_model_zip_data_set_id) REFERENCES print_model (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE watcher_roles
    ADD CONSTRAINT fkl4u1471tc9dfgqg6fos7o8dhg FOREIGN KEY (watcher_id) REFERENCES watcher (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE print_model_oth_web
    ADD CONSTRAINT fkr7agos2vmx7o0ei0y6u4il7m1 FOREIGN KEY (model_oth_list_id) REFERENCES print_model_web (id) ON UPDATE NO ACTION ON DELETE NO ACTION;